# Generated by Django 4.0.5 on 2022-06-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taxPrice',
            new_name='vatPrice',
        ),
    ]
